"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 21:31:32.605062
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=15), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=True),
        sa.CheckConstraint("role = 'super_admin' OR department IS NOT NULL", name=op.f("ck_admins_department")),
        sa.CheckConstraint("role IN ('super_admin', 'admin')", name=op.f("ck_admins_role")),
        sa.PrimaryKeyConstraint("email", name=op.f("pk_admins")),
    )
    op.create_table(
        "app_state",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_state")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), sa.Identity(always=False), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("team_code", sa.String(length=12), nullable=True),
        sa.Column("department", sa.String(length=20), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(op.f("ix_audit_log_department"), "audit_log", ["department"], unique=False)
    op.create_index(op.f("ix_audit_log_team_id"), "audit_log", ["team_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cognito_sub", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("cognito_sub", name=op.f("uq_users_cognito_sub")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=False),
        sa.Column("participant_type", sa.String(length=10), nullable=False),
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("institution_key", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=True),
        sa.Column("course", sa.String(length=40), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("roll_number", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("participant_type IN ('kiet', 'college', 'school')", name=op.f("ck_profiles_participant_type")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
    )
    op.create_index(op.f("ix_profiles_department"), "profiles", ["department"], unique=False)
    op.create_index(op.f("ix_profiles_institution_key"), "profiles", ["institution_key"], unique=False)
    op.create_index(
        "uq_profiles_kiet_roll_number",
        "profiles",
        ["roll_number"],
        unique=True,
        postgresql_where=sa.text("participant_type = 'kiet'"),
        sqlite_where=sa.text("participant_type = 'kiet'"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("name_key", sa.String(length=40), nullable=False),
        sa.Column("category", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=80), nullable=False),
        sa.Column("project_title", sa.String(length=120), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("participant_type", sa.String(length=10), nullable=False),
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("institution_key", sa.String(length=200), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=True),
        sa.Column("route", sa.String(length=10), nullable=False),
        sa.Column("leader_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("result", sa.String(length=15), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("result IN ('pending', 'finalist', 'not_selected')", name=op.f("ck_teams_result")),
        sa.CheckConstraint("route IN ('department', 'finale')", name=op.f("ck_teams_route")),
        sa.CheckConstraint("status IN ('draft', 'submitted', 'withdrawn', 'disqualified')", name=op.f("ck_teams_status")),
        sa.CheckConstraint("category BETWEEN 1 AND 8", name=op.f("ck_teams_category")),
        sa.ForeignKeyConstraint(["leader_id"], ["users.id"], name=op.f("fk_teams_leader_id_users"), ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("name_key", name=op.f("uq_teams_name_key")),
        sa.UniqueConstraint("number", name=op.f("uq_teams_number")),
    )
    op.create_index(op.f("ix_teams_category"), "teams", ["category"], unique=False)
    op.create_index(op.f("ix_teams_department"), "teams", ["department"], unique=False)
    op.create_index(op.f("ix_teams_participant_type"), "teams", ["participant_type"], unique=False)
    op.create_index(op.f("ix_teams_status"), "teams", ["status"], unique=False)
    op.create_table(
        "finalist_nominations",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=False),
        sa.Column("category", sa.Integer(), nullable=False),
        sa.Column("nominated_by", sa.String(length=320), nullable=False),
        sa.Column("nominated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_finalist_nominations_team_id_teams"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", name=op.f("pk_finalist_nominations")),
    )
    op.create_index(op.f("ix_finalist_nominations_department"), "finalist_nominations", ["department"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'cancelled')", name=op.f("ck_invitations_status")),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], name=op.f("fk_invitations_invited_by_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_invitations_team_id_teams"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
    )
    op.create_index("ix_invitations_email_status", "invitations", ["email", "status"], unique=False)
    op.create_index(op.f("ix_invitations_team_id"), "invitations", ["team_id"], unique=False)
    op.create_index(
        "uq_invitations_pending",
        "invitations",
        ["team_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('leader', 'member')", name=op.f("ck_team_members_role")),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_team_members_team_id_teams"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_team_members_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "user_id", name=op.f("pk_team_members")),
        sa.UniqueConstraint("user_id", name=op.f("uq_team_members_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_members")
    op.drop_index(
        "uq_invitations_pending",
        table_name="invitations",
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_invitations_team_id"), table_name="invitations")
    op.drop_index("ix_invitations_email_status", table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_finalist_nominations_department"), table_name="finalist_nominations")
    op.drop_table("finalist_nominations")
    op.drop_index(op.f("ix_teams_status"), table_name="teams")
    op.drop_index(op.f("ix_teams_participant_type"), table_name="teams")
    op.drop_index(op.f("ix_teams_department"), table_name="teams")
    op.drop_index(op.f("ix_teams_category"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(
        "uq_profiles_kiet_roll_number",
        table_name="profiles",
        postgresql_where=sa.text("participant_type = 'kiet'"),
        sqlite_where=sa.text("participant_type = 'kiet'"),
    )
    op.drop_index(op.f("ix_profiles_institution_key"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_department"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("users")
    op.drop_index(op.f("ix_audit_log_team_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_department"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("app_state")
    op.drop_table("admins")
    # ### end Alembic commands ###
